### ISSUE TITLE
Corrections to README.md

### ISSUE THREAD

**Issue by dennisschultz-db** [digexp/MACM-SDK-iOS#1]
Reading through the README.md, I found a few things I think should be corrected or could be made more clear.

Under **Install CocoaPods**, it says "You need CocoaPods to install CAASObjC" but it isn't clear who will need CAASObjC.  Existing apps?  New apps?

The sections **Install CocoaPods** and **Running the sample** are repeated.

I believe **Using in your project** is meant to apply only to existing projects, not the sample project.  This should be more clear.  This section also repeats the instructions for installing and initializing CocoaPods a third time.  

Section **Authentication** - "adressing" is misspelled.  should be "addressing".  
It isn't clear from this information why one would use application credentials or why one would use end user credentials.  There should probably be more explanation.
"harcoded" should be "hard-coded".
Thanks.

**Comment by patrickruzand** [comment]
README updated accordingly. Thanks for the feedback.
