### ISSUE TITLE
No such module 'Shimmer'

### ISSUE THREAD

**Issue by dennisschultz-db** [digexp/MACM-SDK-iOS#2]
Project will not build in XCode 7.0.1 when cloned.

**Comment by lizeray** [comment]
Yes it builds. Make sure to run pod install and open the workspace, not the project.

Btw, we only support the last official release of XCode, that is Xcode 7.1 today. I recommend you to use the last XCode official release. But this is not related to your issue.

**Comment by dennisschultz-db** [comment]
Thanks. I suggest you include "open the workspace" in the README.md.
